### ISSUE TITLE
Calculator Equals Key Error

### ISSUE THREAD

**Issue by jakhuyen** [Ediful/Calculator#1]
When pressing enter after completing an operation, the behavior does not reflect the intended functionality. For example:

Current Behavior
2 + 5     = 7    Press Equals
7 + 7     = 14  Press Equals
14 + 14 = 28

Expected Behavior
2 + 5   = 7   Press Equals
7 + 5   = 12 Press Equals
12 + 5 = 17

This applies to all operators +,-,*,/

**Comment by Ediful** [comment]
Okie dokie i'll get right on that ;)
